export const jobDesc = {
  uiux: {
    data01: {
      jobTitle: "Criação de imagem conceito",
      companyName: "C3Tech",
      jobDescription:
        "Desenvolvimento de conceito para a marca C3Tech, com foco na criação do site institucional e e-commerce",
      tools: [
        "Figma",
        "Scketch",
        "Adobe Photoshop",
        "Adobe Illustrator",
        "React js",
        "Tailwind CSS",
        "node",
        "Firebase",
        "VPS",
        "SSH",
        "Docker",
        "vscode",
      ],
      data: "2021",
    },
    data02: {
      jobTitle: "Criação de imagem conceito",
      companyName: "Grupo Skill",
      jobDescription:
        "Desenvolvimento de conceito para a marca do Grupo Skill, com foco na criação do site institucional e e-commerce",
      tools: [
        "Figma",
        "Scketch",
        "Adobe Photoshop",
        "Adobe Illustrator",
        "React js",
        "Tailwind CSS",
        "Material Design",
        "Bootstrap",
        "Wordpress",
        "php",
        "node",
        "Firebase",
        "VPS",
        "SSH",
        "Docker",
        "vscode",
      ],
      data: "2021",
    },
    data03: {
      jobTitle: "Criação de site",
      companyName: "EVG",
      jobDescription:
        "Desenvolvimento de site conceito para o disco resist do artista EVG.",
      tools: ["Figma", "vscode", "firebase"],
      data: "2021",
    },
    data04: {
      jobTitle: "Proposta de redesign do app",
      companyName: "Overcast",
      jobDescription: "Proposta de modernização do app.",
      tools: ["Figma", "vscode"],
      data: "2021",
    },
    data05: {
      jobTitle: "Criação de imagem conceito",
      companyName: "Wellness",
      jobDescription:
        "Desenvolvimento de site para a marca Wellness, com o objetivo de criar uma conexão com os clientes e que representasse os valores da marca e seus produtos.",
      tools: ["Figma", "vscode"],
      data: "2021",
    },
    data06: {
      jobTitle: "Criação de site de portfólio",
      companyName: "Seeking 4 elements",
      jobDescription:
        "Desenvolvimento de site para o fotografo com o objetivo de criar um portfólio online.",
      tools: ["Figma", "Adobe Photoshop", "vscode"],
      data: "2021",
    },
  },
  impressos: {
    data01: {
      jobTitle: "Criação de cardápio",
      companyName: "Tapera",
      jobDescription: "Desenvolvimento do layout do cardápio e impressão. ",
      tools: ["Adobe Photoshop", "Adobe Illustrator"],
      data: "2021",
    },
    data02: {
      jobTitle: "Criação de catálogo de produtos",
      companyName: "Miroa",
      jobDescription:
        "Criação e desenvolvimento de catálogo da coleção de biquines para a marca Miroa.",
      tools: ["Adobe Photoshop", "Adobe Illustrator"],
      data: "2021",
    },
    data03: {
      jobTitle: "Criação de material de papelaria",
      companyName: "Aponta Facil",
      jobDescription: "Desenvolvimento de panfletos para a marca aponta facil.",
      tools: ["Adobe Photoshop", "Adobe Illustrator"],
      data: "2021",
    },
    data04: {
      jobTitle: "Criação de catálogo de produtos",
      companyName: "Coletek",
      jobDescription: "Criação de catálogo de produtos para a marca Coletek.",
      tools: ["Adobe Photoshop", "Adobe Illustrator"],
      data: "2021",
    },
    data05: {
      jobTitle: "Criação de material de papelaria",
      companyName: "Rede D'or",
      jobDescription: "Desenvolvimento de materiais diversos para a Rede D'Or",
      tools: ["Adobe Photoshop", "Adobe Illustrator"],
      data: "2021",
    },
    data06: {
      jobTitle: "Criação de material de papelaria",
      companyName: "Grupo Skill",
      jobDescription:
        "Criação e desenvolvimento de papelaria para o Grupo Skill.",
      tools: ["Adobe Photoshop", "Adobe Illustrator"],
      data: "2021",
    },
  },
  branding: {
    data01: {
      jobTitle: "Criação da marca",
      companyName: "Galdino Doces",
      jobDescription:
        "Criação da marca e desenvolvimento da identidade visual. ",
      tools: ["Adobe Photoshop", "Adobe Illustrator"],
      data: "2021",
    },
    data02: {
      jobTitle: "Criação da marca",
      companyName: "Docpay",
      jobDescription: "Criação e desenvolvimento da marca.",
      tools: ["Adobe Photoshop", "Adobe Illustrator"],
      data: "2021",
    },
    data03: {
      jobTitle: "Criação de material de papelaria",
      companyName: "Triple One",
      jobDescription: "Criação e desenvolvimento da marca.",
      tools: ["Adobe Photoshop", "Adobe Illustrator"],
      data: "2021",
    },
    data04: {
      jobTitle: "Criação de catálogo de produtos",
      companyName: "C3Tech",
      jobDescription: "Criação e desenvolvimento da marca.",
      tools: ["Adobe Photoshop", "Adobe Illustrator"],
      data: "2021",
    },
    data05: {
      jobTitle: "Criação de material de papelaria",
      companyName: "Grupo Skill",
      jobDescription: "Criação e desenvolvimento da marca.",
      tools: ["Adobe Photoshop", "Adobe Illustrator"],
      data: "2021",
    },
    data06: {
      jobTitle: "Criação de material de papelaria",
      companyName: "Tapera",
      jobDescription: "Criação e desenvolvimento da marca.",
      tools: ["Adobe Photoshop", "Adobe Illustrator"],
      data: "2021",
    },
  },
  foto: {
    data01: {
      jobTitle: "Fotografia de eventos",
      companyName: "Monologo de uma mulher(SESC)",
      jobDescription:
        "Fotografias cobrindo a peça de teatro Monologo de uma mulher, no SESC Pinheiros.",
      tools: ["Adobe Photoshop", "Adobe Lightroom"],
      data: "2021",
    },
    data02: {
      jobTitle: "Fotografia de eventos",
      companyName: "Eventos Sociais - Aniversários",
      jobDescription: "Fotografias de cobertura de festas de aniversários.",
      tools: ["Adobe Photoshop", "Adobe Lightroom"],
      data: "2021",
    },
    data03: {
      jobTitle: "Fotografia de eventos",
      companyName: "Eventos Sociais - Casamentos",
      jobDescription: "Fotografias de cobertura de festas de casamento.",
      tools: ["Adobe Photoshop", "Adobe Lightroom"],
      data: "2021",
    },
    data04: {
      jobTitle: "Fotográfias para catálogo de produtos",
      companyName: "Catálogo de coleção MIROA",
      jobDescription:
        "Sessões de fotografia com modelo para criação de catalogo de produtos.",
      tools: ["Adobe Photoshop", "Adobe Lightroom"],
      data: "2021",
    },
    data05: {
      jobTitle: "Fotografias para criação de material de marketing ",
      companyName: "Buddah Spa",
      jobDescription:
        "Ensaios fotograficos com os espaços e serviços do Buddah Spa.",
      tools: ["Adobe Photoshop", "Adobe Lightroom"],
      data: "2021",
    },
    data06: {
      jobTitle: "Fotografias artisticas",
      companyName: "Diversos",
      jobDescription: "Fotografias artisticas diversas.",
      tools: ["Adobe Photoshop", "Adobe Lightroom"],
      data: "2021",
    },
  },
  edicao: {
    data01: {
      jobTitle: "Captação e edição de video",
      companyName: "Emporio Tartufi",
      jobDescription:
        "Captação e edição de video para a marca Emporio Tartufi.",
      tools: [
        "Iluminação",
        "Roteiro",
        "Direção",
        "Captação Nikon e Canon",
        "Adobe Premiere",
        "Adobe Lightroom",
      ],
      data: "2021",
    },
    data02: {
      jobTitle: "Criação de video institucional",
      companyName: "Triple One",
      jobDescription: "Criação de video institucional para a marca Triple One.",
      tools: ["Adobe Premiere", "Adobe Lightroom"],
      data: "2021",
    },
    data03: {
      jobTitle: "Captação e edição de video",
      companyName: "C3Tech",
      jobDescription: "Captação e edição de videos de lançamento de produtos.",
      tools: ["Adobe Premiere", "Adobe AfterEffects"],
      data: "2021",
    },
    data04: {
      jobTitle: "Captação e edição de video",
      companyName: "C3Tech",
      jobDescription: "Captação e edição de videos de lançamento de produtos.",
      tools: ["Adobe Premiere", "Adobe AfterEffects"],
      data: "2021",
    },
    data05: {
      jobTitle: "Captação e edição de video",
      companyName: "C3Tech",
      jobDescription: "Captação e edição de videos de lançamento de produtos.",
      tools: ["Adobe Premiere", "Adobe AfterEffects"],
      data: "2021",
    },
    data06: {
      jobTitle: "Criação de video institucional",
      companyName: "Grupo Skill",
      jobDescription: "Captação e edição de video institucional.",
      tools: ["Adobe Premiere", "Adobe AfterEffects"],
      data: "2021",
    },
  },
};
