export const jobDesc = {
  uiux: {
    data01: {
        jobTitle: "Criação de imagem conceito",
        companyName: "C3Tech",
        jobDescription: "Desenvolvimento de conceito para a marca C3Tech, com foco na criação do site institucional e e-commerce",
        tools: ["Figma", "Adobe Photoshop", "Adobe Illustrator", 'vscode'],
        data: "2021",
    },
    data02: {
        jobTitle: "Criação de imagem conceito",
        companyName: "Grupo Skill",
        jobDescription: "Desenvolvimento de conceito para a marca do Grupo Skill, com foco na criação do site institucional e e-commerce",
        tools: ["Figma", "Adobe Photoshop", "Adobe Illustrator", 'vscode'],
        data: "2021",
    },
    data03: {
        jobTitle: "ReDesign de site",
        companyName: "Skill Consulting",
        jobDescription: "Desenvolvimento do site de faq da Skill Consulting.",
        tools: ["Figma", "vscode"],
        data: "2021",
    },
    data04: {
        jobTitle: "Proposta de redesign do app",
        companyName: "Overcast",
        jobDescription: "Proposta de modernização do app.",
        tools: ["Figma", "vscode"],
        data: "2021",
    },
    data05: {
        jobTitle: "Criação de imagem conceito",
        companyName: "Wellness",
        jobDescription: "Desenvolvimento de site para a marca Wellness, com o objetivo de criar uma conexão com os clientes e que representasse os valores da marca e seus produtos.",
        tools: ["Figma", "vscode"],
        data: "2021",
    },
    data06: {
        jobTitle: "Criação de site de portfólio",
        companyName: "Welton Carvalho",
        jobDescription: "Desenvolvimento de site para o fotografo com o objetivo de criar um portfólio online.",
        tools: ["Figma", "Adobe Photoshop", 'vscode'],
        data: "2021",
    },
    
  },
  impressos: {
    img1: "https://www.koncretejungle.com.br/eloygomes/assets/port/portCovers/02%20-%20impressos/impressos06.png",
    img2: "https://www.koncretejungle.com.br/eloygomes/assets/port/portCovers/02%20-%20impressos/impressos05.png",
    img3: "https://www.koncretejungle.com.br/eloygomes/assets/port/portCovers/02%20-%20impressos/impressos04.png",
    img4: "https://www.koncretejungle.com.br/eloygomes/assets/port/portCovers/02%20-%20impressos/impressos03.png",
    img5: "https://www.koncretejungle.com.br/eloygomes/assets/port/portCovers/02%20-%20impressos/impressos02.png",
    img6: "https://www.koncretejungle.com.br/eloygomes/assets/port/portCovers/02%20-%20impressos/impressos01.png",
  },
  branding: {
    img1: "https://www.koncretejungle.com.br/eloygomes/assets/port/portCovers/03%20-%20branding/branding06.png",
    img2: "https://www.koncretejungle.com.br/eloygomes/assets/port/portCovers/03%20-%20branding/branding05.png",
    img3: "https://www.koncretejungle.com.br/eloygomes/assets/port/portCovers/03%20-%20branding/branding04.png",
    img4: "https://www.koncretejungle.com.br/eloygomes/assets/port/portCovers/03%20-%20branding/branding03.png",
    img5: "https://www.koncretejungle.com.br/eloygomes/assets/port/portCovers/03%20-%20branding/branding02.png",
    img6: "https://www.koncretejungle.com.br/eloygomes/assets/port/portCovers/03%20-%20branding/branding01.png",
  },
  foto: {
    img1: "https://www.koncretejungle.com.br/eloygomes/assets/port/portCovers/04%20-%20foto/foto06.png",
    img2: "https://www.koncretejungle.com.br/eloygomes/assets/port/portCovers/04%20-%20foto/foto05.png",
    img3: "https://www.koncretejungle.com.br/eloygomes/assets/port/portCovers/04%20-%20foto/foto04.png",
    img4: "https://www.koncretejungle.com.br/eloygomes/assets/port/portCovers/04%20-%20foto/foto03.png",
    img5: "https://www.koncretejungle.com.br/eloygomes/assets/port/portCovers/04%20-%20foto/foto02.png",
    img6: "https://www.koncretejungle.com.br/eloygomes/assets/port/portCovers/04%20-%20foto/foto01.png",
  },
  edicao: {
    img1: "https://www.koncretejungle.com.br/eloygomes/assets/port/portCovers/05%20-%20edicao/edicao06.png",
    img2: "https://www.koncretejungle.com.br/eloygomes/assets/port/portCovers/05%20-%20edicao/edicao05.png",
    img3: "https://www.koncretejungle.com.br/eloygomes/assets/port/portCovers/05%20-%20edicao/edicao04.png",
    img4: "https://www.koncretejungle.com.br/eloygomes/assets/port/portCovers/05%20-%20edicao/edicao03.png",
    img5: "https://www.koncretejungle.com.br/eloygomes/assets/port/portCovers/05%20-%20edicao/edicao02.png",
    img6: "https://www.koncretejungle.com.br/eloygomes/assets/port/portCovers/05%20-%20edicao/edicao01.png",
  },
};
