export const translations = {
  "pt-br": {
    meta: { description: "Portfólio de Eloy Gomes, Software Engineer e Full Stack Developer." },
    a11y: { skip: "Ir para o conteúdo", menu: "Abrir menu", language: "Selecionar idioma" },
    nav: { bio: "Bio", portfolio: "Portfólio", career: "Carreira", services: "Serviços", contact: "Contato", resume: "Currículo" },
    hero: { eyebrow: "Software Engineer · São Paulo", titleA: "Código com", titleB: "visão de design.", intro: "Crio produtos digitais conectando engenharia de software, interfaces e pensamento visual.", projects: "Ver projetos", contact: "Falar comigo", scroll: "Role para explorar" },
    bio: { label: "01 / Perfil", title: "Entre design, produto e engenharia.", lead: "Transformo ideias e problemas complexos em produtos digitais claros, funcionais e visualmente consistentes — da interface à infraestrutura.", education: "Formação multidisciplinar", educationText: "Formado em Design Gráfico e graduando em Engenharia de Software, combino fundamentos visuais, experiência do usuário e engenharia na construção de produtos digitais.", digital: "Desenvolvimento ponta a ponta", digitalText: "Desde 2019, desenvolvo aplicações web e mobile, trabalhando entre interfaces, APIs, bancos de dados, integrações e infraestrutura.", creative: "Visão de produto", creativeText: "Minha experiência anterior com design, direção de arte e e-commerce influencia a forma como desenvolvo: tecnologia não apenas como código, mas como parte de uma experiência completa.", areas: "Áreas", stack: "Tecnologias" },
    portfolio: { label: "02 / PORTFOLIO", title: "Projetos que unem produto, interface e código.", open: "Ver case study", all: "Ver todos os projetos" },
    career: { label: "03 / Carreira", title: "Uma carreira construída entre design e desenvolvimento.", tools: "Ferramentas", details: "Ver detalhes da experiência", responsibilities: "Atribuições", location: "Localização" },
    services: { label: "04 / Serviços", title: "Como posso ajudar o seu projeto?", front: "Front-End", frontText: "Landing pages, sites completos, e-commerces e dashboards com foco em usabilidade, acessibilidade e experiência do usuário em qualquer dispositivo.", back: "Back-End", backText: "APIs REST eficientes, comunicação em tempo real via WebSockets e manipulação de bancos de dados SQL e NoSQL para dar sustentação completa ao seu sistema.", mobile: "Mobile", mobileText: "Apps híbridos para Android e iOS usando React Native/Expo, compartilhando uma base de código única e entregando experiência nativa.", desktop: "Desktop", desktopText: "Apps desktop multiplataforma (Windows, Linux, macOS) com Python e React Native, incluindo integrações com APIs, bancos remotos e sistemas existentes.", technical: "Soluções Técnicas", technicalText: "Arquitetura escalável, microserviços, gerenciamento de estado (Redux), CI/CD para deploys contínuos e automações com n8n e orquestradores.", data: "Análise de Dados", dataText: "Coleta, processamento e visualização de dados para insights acionáveis, utilizando ferramentas como Python, Pandas e Tableau." },
    contact: { label: "05 / Contato", title: "Vamos construir algo relevante.", text: "Estou disponível para novas parcerias e desafios criativos.", email: "Enviar e-mail" },
    resume: { title: "Currículo", intro: "Software Engineer e Full Stack Developer com formação também em Design Gráfico.", experience: "Experiência", education: "Formação", technologies: "Tecnologias", download: "Baixar PDF", back: "Voltar ao portfólio" },
    case: { back: "Todos os projetos", role: "Papel", type: "Tipo", stack: "Stack", timeline: "Período", status: "Status", context: "Contexto", challenge: "Desafio", solution: "Solução", process: "Decisões de desenvolvimento", gallery: "Telas e detalhes", live: "Visitar projeto", next: "Próximo projeto", provisional: "Texto provisório — conteúdo gerado" }
  },
  en: {
    meta: { description: "Portfolio of Eloy Gomes, Software Engineer and Full Stack Developer." },
    a11y: { skip: "Skip to content", menu: "Open menu", language: "Select language" },
    nav: { bio: "Bio", portfolio: "Portfolio", career: "Career", services: "Services", contact: "Contact", resume: "Résumé" },
    hero: { eyebrow: "Software Engineer · São Paulo", titleA: "Code with a", titleB: "designer’s eye.", intro: "I build digital products by connecting software engineering, interfaces and visual thinking.", projects: "View projects", contact: "Contact me", scroll: "Scroll to explore" },
    bio: { label: "01 / Profile", title: "Between design, product and engineering.", lead: "I turn ideas and complex problems into clear, functional and visually consistent digital products — from interface to infrastructure.", education: "Multidisciplinary background", educationText: "With a degree in Graphic Design and currently studying Software Engineering, I combine visual foundations, user experience and engineering to build digital products.", digital: "End-to-end development", digitalText: "Since 2019, I have developed web and mobile applications, working across interfaces, APIs, databases, integrations and infrastructure.", creative: "Product vision", creativeText: "My previous experience in design, art direction and e-commerce shapes how I build: technology not only as code, but as part of a complete experience.", areas: "Areas", stack: "Technologies" },
    portfolio: { label: "02 / PORTFOLIO", title: "Projects connecting product, interface and code.", open: "View case study", all: "View all projects" },
    career: { label: "03 / Career", title: "A career built between design and development.", tools: "Tools", details: "Experience details", responsibilities: "Responsibilities", location: "Location" },
    services: { label: "04 / Services", title: "How can I help your project?", front: "Front-End", frontText: "Landing pages, complete websites, e-commerce and dashboards focused on usability, accessibility and user experience on any device.", back: "Back-End", backText: "Efficient REST APIs, real-time communication via WebSockets and SQL/NoSQL database management to fully support your system.", mobile: "Mobile", mobileText: "Hybrid Android and iOS apps using React Native/Expo, sharing a single codebase and delivering a native experience.", desktop: "Desktop", desktopText: "Cross-platform desktop apps (Windows, Linux, macOS) with Python and React Native, including integrations with APIs, remote databases and existing systems.", technical: "Technical Solutions", technicalText: "Scalable architecture, microservices, state management (Redux), CI/CD for continuous deployments and automation with n8n and orchestrators.", data: "Data Analysis", dataText: "Data collection, processing and visualization for actionable insights, using tools such as Python, Pandas and Tableau." },
    contact: { label: "05 / Contact", title: "Let’s build something meaningful.", text: "I’m available for new partnerships and creative challenges.", email: "Send an email" },
    resume: { title: "Résumé", intro: "Software Engineer and Full Stack Developer with a background in Graphic Design.", experience: "Experience", education: "Education", technologies: "Technologies", download: "Download PDF", back: "Back to portfolio" },
    case: { back: "All projects", role: "Role", type: "Type", stack: "Stack", timeline: "Timeline", status: "Status", context: "Context", challenge: "Challenge", solution: "Solution", process: "Development decisions", gallery: "Screens and details", live: "Visit project", next: "Next project", provisional: "Provisional copy — generated content" }
  },
  es: {
    meta: { description: "Portafolio de Eloy Gomes, Software Engineer y Full Stack Developer." },
    a11y: { skip: "Ir al contenido", menu: "Abrir menú", language: "Seleccionar idioma" },
    nav: { bio: "Bio", portfolio: "Portafolio", career: "Carrera", services: "Servicios", contact: "Contacto", resume: "Currículum" },
    hero: { eyebrow: "Software Engineer · São Paulo", titleA: "Código con", titleB: "visión de diseño.", intro: "Creo productos digitales conectando ingeniería de software, interfaces y pensamiento visual.", projects: "Ver proyectos", contact: "Contactarme", scroll: "Desplázate para explorar" },
    bio: { label: "01 / Perfil", title: "Entre diseño, producto e ingeniería.", lead: "Transformo ideas y problemas complejos en productos digitales claros, funcionales y visualmente consistentes — de la interfaz a la infraestructura.", education: "Formación multidisciplinar", educationText: "Graduado en Diseño Gráfico y estudiante de Ingeniería de Software, combino fundamentos visuales, experiencia de usuario e ingeniería para crear productos digitales.", digital: "Desarrollo de punta a punta", digitalText: "Desde 2019 desarrollo aplicaciones web y móviles, trabajando entre interfaces, APIs, bases de datos, integraciones e infraestructura.", creative: "Visión de producto", creativeText: "Mi experiencia previa en diseño, dirección de arte y e-commerce influye en cómo desarrollo: tecnología no solo como código, sino como parte de una experiencia completa.", areas: "Áreas", stack: "Tecnologías" },
    portfolio: { label: "02 / PORTFOLIO", title: "Proyectos que unen producto, interfaz y código.", open: "Ver caso de estudio", all: "Ver todos los proyectos" },
    career: { label: "03 / Carrera", title: "Una carrera construida entre diseño y desarrollo.", tools: "Herramientas", details: "Detalles de la experiencia", responsibilities: "Responsabilidades", location: "Ubicación" },
    services: { label: "04 / Servicios", title: "¿Cómo puedo ayudar a tu proyecto?", front: "Front-End", frontText: "Landing pages, sitios completos, e-commerce y dashboards centrados en usabilidad, accesibilidad y experiencia de usuario en cualquier dispositivo.", back: "Back-End", backText: "APIs REST eficientes, comunicación en tiempo real mediante WebSockets y gestión de bases de datos SQL y NoSQL para dar soporte completo a tu sistema.", mobile: "Mobile", mobileText: "Apps híbridas para Android e iOS con React Native/Expo, compartiendo una única base de código y ofreciendo una experiencia nativa.", desktop: "Desktop", desktopText: "Apps de escritorio multiplataforma (Windows, Linux, macOS) con Python y React Native, con integraciones con APIs, bases de datos remotas y sistemas existentes.", technical: "Soluciones Técnicas", technicalText: "Arquitectura escalable, microservicios, gestión de estado (Redux), CI/CD para despliegues continuos y automatizaciones con n8n y orquestadores.", data: "Análisis de Datos", dataText: "Recopilación, procesamiento y visualización de datos para obtener información práctica, utilizando herramientas como Python, Pandas y Tableau." },
    contact: { label: "05 / Contacto", title: "Construyamos algo relevante.", text: "Estoy disponible para nuevas colaboraciones y desafíos creativos.", email: "Enviar email" },
    resume: { title: "Currículum", intro: "Software Engineer y Full Stack Developer con formación también en Diseño Gráfico.", experience: "Experiencia", education: "Formación", technologies: "Tecnologías", download: "Descargar PDF", back: "Volver al portafolio" },
    case: { back: "Todos los proyectos", role: "Rol", type: "Tipo", stack: "Stack", timeline: "Período", status: "Estado", context: "Contexto", challenge: "Desafío", solution: "Solución", process: "Decisiones de desarrollo", gallery: "Pantallas y detalles", live: "Visitar proyecto", next: "Siguiente proyecto", provisional: "Texto provisional — contenido generado" }
  }
} as const;
